---
- name: create {{ service_name }} job
  template: src=rkt_runner.service.j2 dest=/etc/systemd/system/{{ service_name }}.service
  register: install_config

- name: notify systemd of config changes
  command: systemctl daemon-reload
  when: install_config.changed == True

- name: start {{ service_name }} and set to start on startup
  service: name={{ service_name }} state=started enabled=yes
