---
- name: create {{ item.key }} job
  template: src=rkt_runner.service.j2 dest=/etc/systemd/system/{{ item.key }}.service
  register: install_config
  with_dict: "{{ rkt_services }}"

- name: notify systemd of config changes
  command: systemctl daemon-reload
  when: install_config.changed == True

- name: start {{ item.key }} and set to start on startup
  service: name={{ item.key }} state=started enabled=yes
  with_dict: "{{ rkt_services }}"
